name: Graph Build Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build project
        run: |
          make build
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          sudo apt-get install -y 
      - name: Test project
        run: |
          make build-deb
          make test
  artifact:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
      - name: Build project
        run: |
          make build-deb
      - name: Upload Debian package artifact
        uses: actions/upload-artifact@v4
        with:
          name: graph-package
          path: graph-v*.deb
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          sudo apt-get install lintian
      - name: Lint Package
        run: |
          make build-deb
          make lint-deb
